[tool.poetry]
name = "polygon-api-client"
version = "0.0.0"
description = "Official Polygon.io REST and Websocket client."
authors = ["polygon.io"]
license = "MIT"
homepage = "https://polygon.io"
repository = "https://github.com/polygon-io/client-python"
documentation = "https://polygon.io/docs"
keywords = [
  "polygon",
  "free",
  "rest",
  "stock",
  "market",
  "data",
  "api",
  "polygon.io",
  "websocket",
  "client"
]
packages = [
  { include = "polygon" }
]

[tool.poetry.dependencies]
python = "^3.8"
urllib3 = ">=1.26.9,<3"
websockets = ">=10.3,<12"
certifi = ">=2022.5.18"

[tool.poetry.dev-dependencies]
black = "^22.12.0"
mypy = "^1.0"
types-urllib3 = "^1.26.25"
Sphinx = "^5.3.0"
sphinx-rtd-theme = "^1.0.0"
# keep this in sync with docs/requirements.txt for readthedocs.org
sphinx-autodoc-typehints = "^1.19.2"
types-certifi = ">=2021"
types-setuptools = "^67.4.0"
pook = "^1.0.2"
orjson = "^3.8.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
